### ISSUE TITLE
Conceal released v2.0.1

### ISSUE THREAD

**Issue by polysiya** [KaKaVip/secure-preferences#1]
https://github.com/facebook/conceal/releases/tag/v2.0.1

Conceal released v2.0.1 which is faster than previous version with same interface.
I've checked secure-preferences library works well with conceal v2.0.1.

So it would be nice to update README 😄

**Comment by nicolasSchirmer** [comment]
The 2.01 version has a conflict

Error:Conflict with dependency 'com.google.code.findbugs:jsr305' in project ':app'. Resolved versions for app (3.0.2) and test app (2.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by nicolasSchirmer** [comment]
Need the "@aar" at the end, otherwise it will throw an conflict error

compile 'com.facebook.conceal:conceal:2.0.1@aar'

**Comment by DonMat** [comment]
After the update to 2.0.1 you also have to add the information about the initialization of the Conceal.
[IMPORTANT: Initializing the library loader](https://github.com/facebook/conceal#important-initializing-the-library-loader)
Otherwise it does not save the preferences.

**Comment by haipq7641** [comment]
@polysiya Thank you,
@All 
I have updated https://github.com/KaKaVip/secure-preferences/releases/tag/1.1.0
