### ISSUE TITLE
Can't use version 1.1.0

### ISSUE THREAD

**Issue by ductranit** [KaKaVip/secure-preferences#3]
I have a problem when sync version `1.1.0` in gradle
`Failed to resolve: com.github.KaKaVip:secure-preferences:1.1.0`

If you look at [jitpack site](https://jitpack.io/#KaKaVip/secure-preferences), there was a log here: https://jitpack.io/com/github/KaKaVip/secure-preferences/1.1.0/build.log
Please try to fix this issue. Thanks!

**Comment by vad-zuev** [comment]
I second this, wanted to try that lib. Please fix
